version: '3.7'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
  backend:
    container_name: backend
    # volumes:
    #   - './server:/usr/src/app'
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - ./.env