version: '3.7'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    command: ["npm", "run", "start"]
    ports:
      - '3000:3000'
    volumes:
      - './frontend/src:/var/build/frontend/src:delegated'
      - './shared/src:/var/build/shared/src:delegated'
    env_file:
      - .env
  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    command: ["npm", "run", "debug"]
    ports:
      - '8080:8080'
    volumes:
      - './server/src:/workdir/server/src:delegated'
      - './shared/src:/workdir/shared/src:delegated'
    env_file:
      - .env